Repository sef-global/scholarx-frontend, pull requests merged in 2024-10, with the labels that each got.

#202 Making 'Become a Mentor' form to validate number as input value #196
  src/pages/MenteeRegistration/index.tsx
  src/pages/MentorRegistration/MentorRegistration.component.tsx
Labels: hacktoberfest-accepted

#201 Modified mentee registration validations
  src/schemas.ts
Labels: hacktoberfest-accepted

#204 Add the hot.jar cdn link to index.html file
  index.html
Labels: hacktoberfest-accepted

#199 Implement Monthly-checking Feature for Mentees, Mentors and Admins
  package-lock.json
  package.json
  src/App.tsx
  src/assets/svg/Icons/ArrowIcon.tsx
  src/assets/svg/Icons/HistoryClockIcon.tsx
  src/assets/svg/Icons/NewSubmissionsIcon.tsx
  src/assets/svg/Icons/NoCheckInsIcon.tsx
  src/assets/svg/Icons/NotificationBell.tsx
  src/components/MentorCard/MentorCard.component.tsx
  src/components/MonthlyChecking/MenteeCheckInFormModal.component.tsx
  src/components/MonthlyChecking/MenteeMonthlyChecking.tsx
  src/components/MonthlyChecking/MentorFeedbackForm.component.tsx
  src/components/MonthlyChecking/MentorMonthlyChecking.tsx
  src/components/MonthlyChecking/MonthlyCheckingHeader.tsx
  src/components/NotificationBadge/index.tsx
  src/components/Toggle/ButtonToggle.tsx
  src/components/Toggle/HistoryToggle.tsx
  src/components/Toggle/NewSubmissionToggle.tsx
  src/enums.ts
  src/hooks/useSubmitCheckIn.ts
  src/pages/Dashboard/Dashboard.tsx
  src/pages/Dashboard/scenes/OngoingMentorshipPrograms/OngoingMentorshipPrograms.tsx
  src/pages/MenteeApplicationsView/MenteeApplications.component.tsx
  src/pages/MenteeCheckIn/MenteeCheckIn.component.tsx
  src/pages/MenteeCheckIn/MenteeCheckIn.stories.tsx
  src/pages/MenteeDashboard/index.tsx
  src/pages/MyMentees/MyMentees.component.tsx
  src/schemas.ts
  src/types.ts
  src/utils.ts
Labels: frontend, hacktoberfest

#207 Fixed ScholarX logo size in tablet view [fixes #205]
  src/components/Layout/Navbar/index.tsx
Labels: hacktoberfest
